### ISSUE TITLE
Extra closing brackets inserted

### ISSUE THREAD

**Issue by ribrdb** [casualjim/vscode-gotemplate#16]
When using gogo mode, if I type `{{` to start a template tag, vscode inserts three closing brackets. So you end up with something like `{{end}}}`.

**Comment by qin-nz** [comment]
I try to debug this. 
This only occured in normal environment, but not reiterate in `Extension Development Host`.

**Comment by qin-nz** [comment]
This issues is already fix on `master` !
But NOT on [marketplace](https://marketplace.visualstudio.com/items?itemName=casualjim.gotemplate)

@casualjim Pls update marketplace version

For user want to fix it now before marketplace:
Open `$HOME\.vscode\extensions\casualjim.gotemplate-0.3.0\gotemplate.configuration.json`
And modify it as #14

**Comment by casualjim** [comment]
I published 0.4.0

sorry for this. I just forgot
