### ISSUE TITLE
Extension breaks every other one related to HTML files (related/similar to #12)

### ISSUE THREAD

**Issue by bryanpedini** [casualjim/vscode-gotemplate#17]
* Operating System:
  _KUbuntu 19.10_
* Enabled extensions:
  * Go
  * Go Doc
  * gotemplate-syntax
* Expected behavior:
  _Normal HTML (default) snippets working as expected, working default emmet abbreviations, PLUS, syntax highlighting (linting) and code snippets for GoLang inside html templates (from this extension)_
* Expected extension domain:
  * `html` fles
  * `gohtml` files
  * `tmpl` files
* Actual behaviour:
  _Default `html` snippets broken, default emmet abbreviations broken, AND, minimal linting of GoLang code inside `html` templates, with no GoLang snippets or emmet abbreviations_

Please tell me if you need any more informations about my system / configuration to solve this issue.
Bryan.

**Comment by segevfiner** [comment]
The workaround from #12 might only enable emmet. Everything else registered for the HTML language is broken. Similar issues are likely to be seen in other kinds of files supported by this extension.

**Comment by bryanpedini** [comment]
Considering this issue closed due to lack of activity by the repo maintainer (my addition: what a shame!).
