### ISSUE TITLE
Is there a way to set highlight priority for brackets inside qoutes

### ISSUE THREAD

**Issue by kifirkin** [casualjim/vscode-gotemplate#4]
Priority set for html color inside qoutes, but I think it should prioritise template tags inside brackets first
![image](https://cloud.githubusercontent.com/assets/6573628/22879146/b22caa36-f1ed-11e6-896c-3f79708d6870.png)

**Comment by PaluMacil** [comment]
+1

**Comment by hamster1979** [comment]
+++

**Comment by chaimleib** [comment]
When calling functions with string arguments inside HTML attributes, the highlighting breaks with a template's double-quote character.

![screen shot 2018-12-18 at 3 56 41 pm](https://user-images.githubusercontent.com/7785285/50190304-a1f92b00-02dd-11e9-8efe-ec9bb31f0764.png)
